[project]
name = "modelnet10-classifier-dl"
version = "0.1.0"
description = "Classifier with multiple deep learning models for ModelNet10 dataset"
requires-python = ">=3.12"
dependencies = [
    "open3d",
    "numpy",
    "tensorboard",
    "tqdm"
]
